services:
  - type: web
    name: heartai-backend
    env: python
    branch: main
    runtime: python-3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
